repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.7.4  # Use the latest stable version
    hooks:
      - id: ruff
        args: [--fix, "--line-length=88"]
        exclude: |
          (^|/)(
            venv/|
            env/|
            .venv/|
            build/|
            dist/|
            .ipynb_checkpoints/
          )
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: [--line-length=88]
        exclude: |
          (^|/)(
            venv/|
            env/|
            .venv/|
            build/|
            dist/|
            .ipynb_checkpoints/
          )
  - repo: https://github.com/flyersworder/sqlnbfmt
    rev: v0.1.5
    hooks:
      - id: sqlnbfmt
        name: sqlnbfmt
        types: [jupyter]
        args: [--config, config.yaml]
        exclude: |
          (^|/)(
            venv/|
            env/|
            .venv/|
            build/|
            dist/|
            .ipynb_checkpoints/
          )
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-black
        args: [--line-length=88]
        exclude: |
          (^|/)(
            venv/|
            env/|
            .venv/|
            build/|
            dist/|
            .ipynb_checkpoints/
          )
      - id: nbqa-ruff
        args: [--fix, "--line-length=88"]
        exclude: |
          (^|/)(
            venv/|
            env/|
            .venv/|
            build/|
            dist/|
            .ipynb_checkpoints/
          )
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.2.5
    hooks:
      - id: sqlfluff-fix
        args: ["--dialect", "ansi"]
        files: \.sql$  # Only process .sql files
        exclude: |
          (^|/)(
            venv/|
            env/|
            .venv/|
            build/|
            dist/
          )
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.0
    hooks:
      - id: nbstripout
        exclude: |
          (^|/)(
            venv/|
            env/|
            .venv/|
            build/|
            dist/|
            .ipynb_checkpoints/
          )
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: |
          (^|/)(
            venv/|
            env/|
            .venv/|
            build/|
            dist/
          )
      - id: trailing-whitespace
        exclude: |
          (^|/)(
            venv/|
            env/|
            .venv/|
            build/|
            dist/
          )
      - id: check-added-large-files
        args: ["--maxkb=512"]  # Adjust the max file size as needed
        exclude: |
          (^|/)(
            venv/|
            env/|
            .venv/|
            build/|
            dist/
          )
      - id: check-ast
        exclude: |
          (^|/)(
            venv/|
            env/|
            .venv/|
            build/|
            dist/
          )
