format:
  html:
    embed-resources: true
    standalone: true
    html-math-method: katex
    toc: true
    toc-depth: 3
    toc-title: "Chapter Contents"
    toc-location: left
    number-sections: true
    number-depth: 3
    fig-width: 10
    fig-height: 6
    fig-align: center
    theme: cosmo
    smooth-scroll: true
    link-external-newwindow: true

  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true
    fig-format: png
    fig-dpi: 150
    keep-tex: false

execute:
  echo: false
