format:
  html:
    embed-resources: true
    standalone: true
    html-math-method: katex
    toc: true
    toc-depth: 3
    toc-title: "Chapter Contents"
    toc-location: left
    number-sections: true
    number-depth: 3
    fig-width: 10
    fig-height: 6
    fig-align: center
    theme: cosmo
    smooth-scroll: true
    link-external-newwindow: true

execute:
  echo: false

  pdf:
    documentclass: book
    classoption: [11pt, oneside]
    geometry:
      - top=1in
      - bottom=1in
      - left=1.25in
      - right=1.25in
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 3
    fig-width: 7
    fig-height: 5
    fig-pos: 'htbp'
    keep-tex: true
